### ISSUE TITLE
adonis serve --dev taking more than average time for reload

### ISSUE THREAD

**Issue by deathlover** [adonisjs/adonis-framework#983] opened 2018-10-21 08:20 UTC
Adonis Version: 4.1
Node Version: 10.10.0

Scenario 1:
**Command: adonis serve --dev**

The server takes too much to reload, which is getting difficult for the development.

Scenario 2:
**Command: nodemon server.js**
with the configuration as:

```
{
  "restartable": "rs",
  "ignore": [
    ".git",
    "node_modules/**/node_modules",
    "node_modules/*",
    "public/*"
  ],
  "verbose": true,
  "execMap": {
    "js": "node --harmony",
    "rb": "ruby",
	"pde": "processing --sketch={{pwd}} --run"
  },
  "events": {
    "restart": "javascript -e 'display notification \"App restarted due to:\n'$FILENAME'\" with title \"nodemon\"'"
  },
  "watch": [
    "app"
  ],
  "env": {
    "NODE_ENV": "development"
  },
  "ext": "js,json"
}

```
It reduces the time for reload by almost 30%, still unable to figure it out, what is causing the long pause for the server reload.

**Note: The average time is 2-4 seconds**

**Comment by thetutlage** [comment] 2018-10-24 17:51
Closing, since it's not actionable and neither I can reproduce this. Feel free to open, if you have specifics on why it is slow

**Closed by thetutlage** 2018-10-24 17:51 UTC
Labels: triage

**Comment by deathlover** [comment] 2018-10-26 08:37
Sorry for the late reply,

It seems to be a problem with node version 10.10.0, after rollbacking to node 8.12.0(LTS),

Following are the statistics:
Adonis Version (4.1) - Restart time is quite decent

Adonis Version (3):
Error logs are printed now
Restart time is quite decent
