### ISSUE TITLE
How to reproduce the algorithm ON DUPLICATE KEY UPDATE?

### ISSUE THREAD

**Issue by cawa-93** [adonisjs/adonis-framework#519] opened 2017-03-19 16:00 UTC
I have a table with users options:
```
------------------------------------------------------
|    id     |    option_id     |    option_value     |
------------------------------------------------------
```
I want to update a row in a table with one command or create a new one if it does not already exist.
```mysql
INSERT INTO
  options
SET
  option_id = 'enabled',
  value = 1
ON DUPLICATE KEY UPDATE
  value = 1
```
How to achieve this result using Lucid or Query Builder?

**Comment by thetutlage** [comment] 2017-03-21 07:16
You can run a raw query.

```js
Database.schema.raw('Your sql query')
```

**Comment by cawa-93** [comment] 2017-03-21 08:11
@thetutlage, wow. Thanks

**Comment by RomainLanz** [comment] 2017-03-21 08:16
Hey @cawa-93!

There's the `save()` method.

* [Lucid save()](http://adonisjs.com/docs/3.2/lucid#_save)

**Comment by cawa-93** [comment] 2017-03-27 18:46
For this, as I understood, you must first find the object. If it does not exist, create. Then save. This requires a few more requests and manipulations, rather than a simple `insertOrUpdate` (In perspective)

**Comment by RomainLanz** [comment] 2017-03-28 06:54
May I ask what's your usecase?

**Comment by cawa-93** [comment] 2017-03-28 07:57
@RomainLanz, Excuse me, but I did not understand what you mean

**Comment by betaWeb** [comment] 2017-03-30 10:13
I think that having a `insertOrUpdate` method could be a good idea, and would simplify  certain usecases.

**Comment by cawa-93** [comment] 2017-04-15 10:32
Example upsert in knex https://github.com/tgriesser/knex/issues/54#issuecomment-294271255

**Comment by cawa-93** [comment] 2017-05-13 09:52
For those who are also interested in this issue, I propose a temporary solution:

```javascript
const pagesData = {
  id: 1,
  name: 'Some page',
  picture: 'https://...',
}
const insert = Database.table('pages').insert(pagesData).toString()
yield Database.schema.raw(insert + ' ON DUPLICATE KEY UPDATE name=VALUES(name), picture=VALUES(picture), update_at=CURRENT_TIMESTAMP')
```

**Comment by thetutlage** [comment] 2017-10-01 08:37
Closing since not a bug, but can be discussed in forum.https://forum.adonisjs.com/

**Closed by thetutlage** 2017-10-01 08:37 UTC
Labels: 4.0
