### ISSUE TITLE
configuration amazon ses

### ISSUE THREAD

**Issue by GlauberF** [adonisjs/adonis-framework#894] opened 2018-06-21 12:00 UTC
in my application I need to use email sending, it was decided to use amazon ses, but in the default settings in mail.js, inside the config folder, there is no example of how to configure amazon ses, someone could send me the configuration code snippet for amazon ses

**Comment by thetutlage** [comment] 2018-06-21 13:37
Duplicate of https://github.com/adonisjs/adonis-mail/issues/27.

Opening multiple issues will not help much

**Closed by thetutlage** 2018-06-21 13:37 UTC
