### ISSUE TITLE
How to get a hash in the url

### ISSUE THREAD

**Issue by marcus-campos** [adonisjs/adonis-framework#1082] opened 2019-05-30 12:32 UTC
I am doing an authentication with a marketplace that redirects me with the following URL: http://domain.com/hook/session#access_token=my_access_token&expires_in=21600&user_id=123456&domains=localhost

I did not get through the request methods, get the following part of url: #access_token=my_access_token&expires_in=21600&user_id=123456&domains=localhost

How can I get this?

**Comment by RomainLanz** [comment] 2019-05-30 17:02
Hey @marcus-campos! 👋 

This is more a question than an issue with the framework itself.
Please use the [forum](https://forum.adonisjs.com) or the [Discord Server](https://discord.gg/vDcEjq6) for this kind of request.

Also, the client is not sending the query after the fragment identifier (`#`). This not Adonis fault but how it was designed.

**Comment by marcus-campos** [comment] 2019-05-30 23:54
Hi @RomainLanz,

All right, the problem that is the largest marketplace in my country, I need to integrate with it ... I'll try to help in Discord, but if you can help me, I'm sure it can be a question of other people

**Comment by RomainLanz** [comment] 2019-05-31 08:48
Actually, I gave you the answer in my latest sentence. The query string after the fragment identifier (`#`) is not sent to the server. Therefore, Adonis never receive it.

**Comment by thetutlage** [comment] 2019-06-07 02:48
Closing since not actionable

**Closed by thetutlage** 2019-06-07 02:48 UTC
Labels: 🤔 Question
