### ISSUE TITLE
[Lucid] get model relationships dynamically

### ISSUE THREAD

**Issue by betaWeb** [adonisjs/adonis-framework#954] opened 2018-09-19 09:18 UTC
Hi,

First of all, thanks for the amazing job you've done on AdonisJS, this is a very plaisant framework to use :1st_place_medal: 

So, I wan't to get relationships of a model dynamically, I've tried the `Model.getRelated('relationship_name')` method, but it doesn't work.. and when I log the model I get, the `$relations` object is empty, whereas this model has many relations.

Here is the method I use in my generic controller to get dynamically a relation : 
```JS
async _getModelByUser(auth) {
    if (!this._user) {
      this._user = await auth.getUser()
    }

    const relationship = this._user.getRelated(
        this._getUserResource() // get relationship name depending of the controller name
    )
    if (relationship) {
      return relationship
    }
    throw new NoRecordException
  }
```

Here is my User model :
```JS
class User extends Model {

   // ...

  observations() {
    return this.hasMany('App/Models/Observation')
  }

   // ...

}
```

And here is a model which has a relation with the User model I try to get dynamically in `_getModelByUser` method :
```JS
class Observation extends Model {

  get table() {
    return 'observations'
  }

  user() {
    return this.belongsTo('App/Models/User')
  }

   // ...

}
```

The `getRelated()` method always returns `undefined` because the `$relations` object on User is always empty.
Is there an another way to get a model relationship dynamically ? Or is my code bad ? :/

Thanks a lot :+1:

**Comment by thetutlage** [comment] 2018-09-19 11:53
The `getRelated` method returns an eagerloaded relationship. However, if you want to fetch the relationship, you must call the method directly.

```js
const result = await this.user[this._getUserResource()].fetch()
```

Also, since your relationship is a hasMany, a simple `if` check is not the right way to find the existence of rows. 


```js
if (result.rows.length) {

}
```

You must first try to understand the difference between `Eagerloading` and fetching relations on demand and also do check the response structure from the database queries, otherwise you will be confused. 

In brief:

1. Anytime Lucid knows that output of query will be only 1 row. Then it returns the `model instance` or `null`, based upon whether the row was found or not.
2. Otherwise for zero rows an `empty array` is returned or an array of rows found in the database.

**Comment by betaWeb** [comment] 2018-09-21 06:42
Thanks for your answer. But I'd like to do many operations like `save`, and if I get the relationship like that `const result = await this.user[this._getUserResource()]`, I can't.

**Comment by thetutlage** [comment] 2018-09-21 07:26
I suggest reading the docs and trying to understand the fundamentals first.

If you fetch a row from the db, then that row already exists. So, how can you create a row using the instance of a row that already exists?

**Comment by thetutlage** [comment] 2018-09-21 07:28
Finally I suggest moving this question to the forum, since it’s not a bug and on forum, you can get help from others also

**Closed by thetutlage** 2018-09-21 07:28 UTC
Labels: 🤔 Question
