### ISSUE TITLE
please adonisjs does not log error

### ISSUE THREAD

**Issue by nwashangai** [adonisjs/adonis-framework#815] opened 2018-03-22 13:27 UTC
## Structuring The Issue
getting internal server error, but adonis doesn't log error even when i purposely created one, how do i see my errors please

**Comment by RomainLanz** [comment] 2018-03-22 13:52
Hey @nwashangai! 👋 

Please, follow the guide into the readme to create your issue.
https://github.com/adonisjs/adonis-framework#issues--pr

**Comment by nwashangai** [comment] 2018-03-22 16:26
@RomainLanz please help me, am just totally new to adonisjs and am really having big problem working around. 
My problem is that syntax and program errors doesn't show up in the console but when I send a request from the clients, I get error 500.
Secondly I have trying to create a login function, but when I try to generate token using the auth.attempt(uid, password), I get an error message which says that the author is not defined
Now I have checked my providers and in auth.js, authenticator has been set to her, 
Do I need to use() the auth at the top or do I need to pass the auth in the login function. 
I just want to be able to login successfully using token.
I have checked so many login examples but none is actually working for me, also the await/yield keywords gives error in my case

Thank you so much, am anticipating for a good reply.

**Comment by nwashangai** [comment] 2018-03-22 16:28
*auth is not defined

**Comment by nwashangai** [comment] 2018-03-22 16:30
*jwt instead of "her"

**Comment by RomainLanz** [comment] 2018-03-22 16:50
It's not because you are new to a framework that shouldn't follow the rules to post an issue. 😛 

> My problem is that syntax and program errors doesn't show up in the console but when I send a request from the clients, I get error 500.

What's the error you have with the 500?

> Secondly I have trying to create a login function, but when I try to generate token using the auth.attempt(uid, password), I get an error message which says that the auth is not defined

I believe you forget to extract the `auth` module from the context that your controller receive.
Take a look at the example I provide bellow.

> I have checked so many login examples but none is actually working for me, also the await/yield keywords gives error in my case

You can find a real login example in the [adonis-blog-demo](https://github.com/adonisjs/adonis-blog-demo/blob/master/app/Controllers/Http/SessionController.js#L16) application.

**Comment by nwashangai** [comment] 2018-03-22 17:24
Thanks, but from the example you referenced me to, do I need to really need pass the session to the function, since am using jwt, 
I mean should I replace 

async store({auth, request, response, session })

With

async store({auth, request, response, jwt})

**Comment by nwashangai** [comment] 2018-03-22 18:36
My error with code 500 is internal server error

**Comment by RomainLanz** [comment] 2018-03-23 07:37
I would recommend you to re-read the documentation about authentication.
http://adonisjs.com/docs/4.1/authentication

Also, please, switch to the forum or to the Discord Server to ask those type of question.
I'm closing this issue since it's not a bug or a feature request.

**Closed by RomainLanz** 2018-03-23 07:37 UTC
