### ISSUE TITLE
Runnning paginate with orderBy gives me an error

### ISSUE THREAD

**Issue by francisjed** [adonisjs/adonis-framework#332] opened 2016-10-21 05:38 UTC
Here is the error message: 
```
"select count(*) as \"total\" from \"payout_transactions\" where \"userId\" = $1 order by \"id\" desc - column \"payout_transactions.id\" must appear in the GROUP BY clause or be used in an aggregate function"
```

here is the code:

```javascript
const transactions = yield PayoutTransaction.query().orderBy('id', 'desc').where('userId', userId).paginate(page, pageSize})
```

**Comment by juanyunis** [comment] 2016-10-22 05:16
This issue happened to me, i had to create a custom paginator, the good thing is that the query works when you use forPage, something like this:
```javascript
 const totalRecords = yield model.query().count(options.sortField)
 const totalPages = Math.ceil(totalRecords[0].count / recordsPerPage)

 let records = yield model.query()
    .orderBy(sorting.sortField, sorting.sortDirection)
    .forPage(page, recordsPerPage)
    .fetch()
 records = records.toJSON()

 const pageData = {
      page: page,
      pageSize: recordsPerPage,
      totalPages: totalPages,
      totalRecords: records.length,
      data: records
 }
```

I hope this gets fixed.

**Comment by thetutlage** [comment] 2016-10-30 11:34
The issue is duplicated on the `adonis-lucid` repo. I am going to close this issue and will keep the other one updated

**Closed by thetutlage** 2016-10-30 11:34 UTC
