### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by obstschale** [adonisjs/adonis-framework#283] opened 2016-09-21 15:17 UTC
I am writing a new app with Adonis and I have an issue. With some Adonis functions. For example `request.auth.attempt()` or `request.file()`. I can use these functions but then something goes wrong, like the login attempt was not successful (wrong credentials) or the maximum file size exceeds then Adonis throws an exception. So far so good.

My question is: How do I handle these things? If something goes wrong I don't want that the user gets redirected to an 400 oder 500 error page. That is not good for the user experience. I would like to redirect back and flash some messages.

My attempt is to wrap the block into a try-catch block to handle these error. But I'm not yet convinced whether this is the best way to do it. Because from Laravel I am used to not handle these exceptions in controller but a separate exception handler takes care.

```js
// Attempt to login with email and password
try {
    const authCheck = yield request.auth.attempt(email, password);
    if (authCheck) {
        return response.redirect('/');
    }
} catch (e) {
    yield request
        .withAll()
        .andWith({errors: [ { message: loginMessage.error } ] })
        .flash();
    yield response.redirect('back');
    return
}
```

So what do you do with exceptions?

PS: I'm new to Node and Adonis so assume I don't know the best practices for JS-Dev :)

**Comment by thetutlage** [comment] 2016-09-21 16:33
When exceptions are raised, AdonisJs internally fires an event which you can listen and do error handling at a global level.

Check this https://github.com/adonisjs/adonis-app/blob/develop/app/Listeners/Http.js#L14 where AdonisJs itself is listening for the event and responds to it.

From where if required, you can build a service which can parse these error in more standard way and redirect the user back.

`adonis-rally`  is a demo project where I can created a service for handling exceptions and creating personalized errors messages. https://github.com/adonisjs/adonis-rally/blob/develop/app/Services/ExceptionParser.js

Also AdonisJs gives exceptions a unique name, so that when handling an exception you have some context. For example: `ModelNotFound`, `PasswordMisMatch`, `InvalidLoginException` etc.

**Comment by indr** [comment] 2016-09-22 11:15
I really recommend to have a look at the `adonis-rally` project @obstschale, helped me a lot.

Thanks @thetutlage for your explanations. What about exceptions thrown in event listeners? I couldn't find a way to consistently catching/handling them, they seem to get swallowed up. Do you have any guidance here?

**Comment by obstschale** [comment] 2016-09-22 12:43
Thx for the help. The `adonis-rally` repo is really useful. I adapted this idea and also check for the Accept header to return different responses for API requests and HTML requests.

```js
// In app/Services/ExceptionParser.js
'use strict'

const ExceptionParser = exports = module.exports = {}

/**
 * handlers is the list of custom handlers to handle exceptions.
 * For example throw new ValidationException can be handled
 * using ValidationException function on the handlers
 * object.
 *
 * @type       {Object}
 */
const jsonHandlers = {
    ValidationException: function (error, request, response) {
        const fields = error.fields
        const status = error.status || 400
        const message = error.message
        response.badRequest({status, message, fields})
    },

    InvalidLoginException: function (error, request, response) {
        const fields = error.fields
        const status = error.status || 401
        const message = error.message
        response.unauthorized({status, message, fields});
    },

    default: function (error, request, response) {
        const message = error.message || 'Something went wrong'
        const status = error.status || 500
        response.status(status).send({status, message})
    }
}

const htmlHandlers = {
    ValidationException: function (error, request, response) {
        const fields = error.fields
        const status = error.status || 400
        const message = error.message
        response.badRequest({status, message, fields})
    },

    InvalidLoginException: function (error, request, response) {
        response.redirect('/login');
    },

    default: function (error, request, response) {
        const message = error.message || 'Something went wrong'
        const status = error.status || 500
        // Somehow this does not work so I leave it off and in app/Listeners/Http.js the view is rendered.
        //   yield response.status(status).sendView('errors/index', {error})
    }
}

/**
 * send method is used to make the final user friendly error
 * and send it back to the user/browser.
 *
 * @param      {Object}  error     The error
 * @param      {Object}  request   The request
 * @param      {Object}  response  The response
 *
 * @public
 */
ExceptionParser.send = (error, request, response) => {
    const type = request.accepts('json', 'html');

    switch (type) {

        case 'json':
            const jsonHandler = jsonHandlers[error.name] || jsonHandlers.default
            jsonHandler(error, request, response);
            break

        case 'html':
            const htmlHandler = htmlHandlers[error.name] || htmlHandlers.default
            htmlHandler(error, request, response);
            break
    }
}
```

```js
// in app/Listeners/Http.js

'use strict'

const Env = use('Env')
const Ouch = use('youch')
const Http = exports = module.exports = {};
const ExceptionParser = use('App/Services/ExceptionParser');


/**
 * handle errors occured during a Http request.
 *
 * @param  {Object} error
 * @param  {Object} request
 * @param  {Object} response
 */
Http.handleError = function * (error, request, response) {

  ExceptionParser.send(error, request, response)


  /**
   * PRODUCTION REPORTER
   */
  const status = error.status || 500
  console.error(error.stack)
  yield response.status(status).sendView('errors/index', {error})
}

/**
 * listener for Http.start event, emitted after
 * starting http server.
 */
Http.onStart = function () {
}
```

**Comment by thetutlage** [comment] 2016-09-23 17:14
Closing since not a bug and more of a discussion. Feel free to move it to Gitter channel. Thanks 😄

**Closed by thetutlage** 2016-09-23 17:14 UTC
Labels: question

**Comment by shmy** [comment] 2017-05-31 08:15
thanks
