### ISSUE TITLE
Accessing Pivot Table's Fields In Many-To-Many Relationships

### ISSUE THREAD

**Issue by mertindervish** [adonisjs/adonis-framework#365] opened 2016-11-13 11:54 UTC
Hi. I'm working with Adonis for a while. I really appreciate your work 😄. Last week I end up making a many-to-many relationship like in the image below.

![Many-To-Many Relationship](http://i.imgur.com/8fwiSbt.jpg)

Lucid allows me to easily add value to pivot table's fields while attaching record (in my case I'm populating familiarity field in portfolio_skill table). But after the relationship is created I can't update it. The only way I found is by using Query builder.

Also when fetching portfolio's skills I need the familiarity field too. I achieved this by creating custom method in Skill Model which fetches familiarity field by using Query builder and attaches it.

Is there a more Adonis™ way of doing these? It will be an honor for me to develop these features (updateExistingPivot and withPivot methods) if they are not yet.

**Comment by RomainLanz** [comment] 2016-11-13 18:27
Duplicate of https://github.com/adonisjs/discussion/issues/2

**Comment by mertindervish** [comment] 2016-11-13 18:35
@RomainLanz Yes. This is because idk where to post this in order to tell the problem to the author of the framework

**Comment by thetutlage** [comment] 2016-11-13 18:38
@mertindervish Yup functionality to update the `pivot_table` and fetch other fields from pivot table are not implemented yet.

It will be adding `withPivot` and `updatePivot` methods. I will move this discussion to the right repo and will implement changes

**Comment by thetutlage** [comment] 2016-11-13 18:38
Issue moved to [adonisjs/adonis-lucid #69](https://github.com/adonisjs/adonis-lucid/issues/69) via [**ZenHub**](https://www.zenhub.com/)

**Closed by thetutlage** 2016-11-13 18:38 UTC
