### ISSUE TITLE
JWT - Error with refresh token

### ISSUE THREAD

**Issue by pirmax** [adonisjs/adonis-framework#822] opened 2018-04-04 09:24 UTC
Hi,

I've a problem with refresh token, I don't modify the code but I have this error:

`2018-04-04T07:40:57.452Z - error: refreshJWTToken - Error: InvalidRefreshToken: E_INVALID_JWT_REFRESH_TOKEN: Invalid refresh token bf4c53cdd9dc51cdsfdf54df5d4f5df454fds6faf546764ed09253fb1211215752d0ec5e855b3aa0d8b1abtq+pMMXjR4C85sC/FOZjSTXYJYD4FD45FDSF4XgF8512asPY8uc8EKe`

I've edited the example of error ;)

`const jwt = await auth.newRefreshToken().generateForRefreshToken(params.refreshToken, true)`

**Comment by RomainLanz** [comment] 2018-04-10 14:51
Hey @pirmax! 👋 

Could you please provide a way to reproduce this issue?

**Comment by thetutlage** [comment] 2018-04-10 15:26
Yup a repo will be nice

**Comment by RomainLanz** [comment] 2018-04-15 12:33
Closing since no answer from issue reporter.

**Closed by RomainLanz** 2018-04-15 12:33 UTC

**Comment by pirmax** [comment] 2018-04-16 07:51
Hi,

I use this repository https://github.com/gammpamm/plasma-nuxt

The problem become when the JWT token is expired (configured in auth.js in config directory).
The token is expired, so, the refresh token is in while refresh... I don't know why :/

Thanks.

**Comment by veakey** [comment] 2018-04-25 11:35
Hi guys,
comming back to this issue ;)

Using the **withRefreshToken** works fine
```javascript
await auth
  .withRefreshToken()
  .attempt(uid, password)
```

The token is created successfully in mongo db but

But when we want to ask a new refresh token (not expired yet for sure since we don't have the **E_JWT_TOKEN_EXPIRED** exception) we have instead

```shell
E_INVALID_JWT_REFRESH_TOKEN: Invalid refresh token
``` 

Digging into @adonijs/auth/src/Schemes/Jwt.js at generateForRefreshToken(line 328)

It seems the use is never found...

So using our proper models in this function resulted in successfully generate the new acces token.
Instead of using current implementation

```javascript
async generateForRefreshToken (refreshToken, jwtPayload, jwtOptions) {
    const user = await this._serializerInstance.findByToken(this.Encryption.decrypt(refreshToken), 'jwt_refresh_token')
    if (!user) {
      throw CE.InvalidRefreshToken.invoke(refreshToken)
    }

    const token = await this.generate(user, jwtPayload, jwtOptions)

    /**
     * If user generated a new refresh token, in that case we
     * should revoke the old one, otherwise we should
     * set the refreshToken as the existing refresh
     * token in the return payload
     */
    if (!token.refreshToken) {
      token.refreshToken = refreshToken
    } else {
      await this.revokeTokensForUser(user, [refreshToken], true)
    }

    return token
  }
```

we just add our models to fetch the target token

```javascript
async generateForRefreshToken (refreshToken, jwtPayload, jwtOptions) {

    const User = use('App/Models/User')
    const UserToken = use('App/Models/UserToken')

    const plainToken = await UserToken.findBy('token', this.Encryption.decrypt(refreshToken))
    const user = await User.find(plainToken.user_id)

    if (!user) {
      throw CE.InvalidRefreshToken.invoke(refreshToken)
    }

    const token = await this.generate(user, jwtPayload, jwtOptions)

    /**
     * If user generated a new refresh token, in that case we
     * should revoke the old one, otherwise we should
     * set the refreshToken as the existing refresh
     * token in the return payload
     */
    if (!token.refreshToken) {
      token.refreshToken = refreshToken
    } else {
      await this.revokeTokensForUser(user, [refreshToken], true)
    }

    return token
  }

```

Do you know why ?

Thanks for your awesome job and your time,

Cheers!

**Comment by saeedcs** [comment] 2018-12-18 09:14
I still have this issue. code repo at https://bitbucket.org/saeedbiz9s/security/src/master/
