### ISSUE TITLE
How to disable database error output in production

### ISSUE THREAD

**Issue by telcy** [adonisjs/adonis-framework#875] opened 2018-06-04 08:01 UTC
### Brief Description
I am not sure if there is any other option to disable database error output in production. I already set NODE_ENV=production but it is still showing me database errors as body result. I know that I have to delete the other data first and that I could also wrap it into a try catch block. But to make sure no data is leaked I would like to know how to disable db errors completely.

Would really appreciate your help

### Error Stack (if any)
`error: delete from "xxx" where "id" = $1 - update or delete on table "xxx" violates foreign key constraint "abc" on table "ccc"`

**Comment by thetutlage** [comment] 2018-06-04 08:03
Can you share the complete error stack?

**Comment by telcy** [comment] 2018-06-04 08:10
### Stacktrace

```text
2018-06-04T08:06:27.353Z - error:  error: update or delete on table "p_applications" violates foreign key constraint "p_notifications_application_id_foreign" on table "p_notifications"
    at Connection.parseE (/Users/jascha/Documents/Projects/pusha/pusha-web/node_modules/pg/lib/connection.js:553:11)
    at Connection.parseMessage (/Users/jascha/Documents/Projects/pusha/pusha-web/node_modules/pg/lib/connection.js:378:19)
    at Socket.<anonymous> (/Users/jascha/Documents/Projects/pusha/pusha-web/node_modules/pg/lib/connection.js:119:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
From previous event:
    at Client_PG._query (/Users/jascha/Documents/Projects/pusha/pusha-web/node_modules/knex/lib/dialects/postgres/index.js:287:12)
    at Client_PG.query (/Users/jascha/Documents/Projects/pusha/pusha-web/node_modules/knex/lib/client.js:206:17)
    at Runner.<anonymous> (/Users/jascha/Documents/Projects/pusha/pusha-web/node_modules/knex/lib/runner.js:155:36)
From previous event:
    at /Users/jascha/Documents/Projects/pusha/pusha-web/node_modules/knex/lib/runner.js:61:21
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Runner.run (/Users/jascha/Documents/Projects/pusha/pusha-web/node_modules/knex/lib/runner.js:47:31)
    at Builder.Target.then (/Users/jascha/Documents/Projects/pusha/pusha-web/node_modules/knex/lib/interface.js:39:43)```

**Comment by thetutlage** [comment] 2018-06-04 08:21
By looking at the exception it does look like a runtime exception.

AdonisJs [exception handling](https://adonisjs.com/docs/4.1/exceptions) let you handle all the exceptions that occur during the HTTP life-cycle at a single place.

If your code is not part of the HTTP lifecycle, then you have to wrap your code inside `try/catch`. Since there is no way to ignore exceptions and neither a good practice to run system by ignoring exceptions.

**Comment by telcy** [comment] 2018-06-04 08:44
NODE_ENV=production
<img width="1659" alt="screen shot 2018-06-04 at 15 43 10" src="https://user-images.githubusercontent.com/3081527/40907455-17176228-680e-11e8-9599-e40a98a44a38.png">

NODE_ENV=development
<img width="1633" alt="screen shot 2018-06-04 at 15 37 56" src="https://user-images.githubusercontent.com/3081527/40907229-61049848-680d-11e8-824f-5494b3541bcd.png">

Thank you for the link regarding exception handlers. I am just wondering why all other Exceptions are hidden in production except this one.

I know that try-catch blocks are good and should be used, but the production environment should also not display any error outputs for the user.

**Comment by thetutlage** [comment] 2018-06-05 08:14
Can you share a sample repo to reproduce the issue. And please only share the minimal required code, since I don't have much time to setup the entire app to debug this issue

**Comment by telcy** [comment] 2018-06-07 00:42
Sure, I will share a sample repo the next days.

**Comment by thetutlage** [comment] 2018-06-18 12:56
Your code doesn't have an exception handler. Which means exceptions are handled in the default way. 

Please read this guide https://adonisjs.com/docs/4.1/exceptions

**Comment by RomainLanz** [comment] 2018-06-22 05:57
Closing since no answer from issue reporter.

**Closed by RomainLanz** 2018-06-22 05:57 UTC
Labels: 🤔 Question
