### ISSUE TITLE
support for mongodb

### ISSUE THREAD

**Issue by webreinvent** [adonisjs/adonis-framework#215] opened 2016-07-23 08:32 UTC
@thetutlage do you have any plan to provide support for mongodb ? if yes then when we can expect it?

**Comment by RomainLanz** [comment] 2016-07-23 09:07
Hi @webreinvent !

This have already been discuss on some issues. Let me link them to you.

* [How to Integrate With MongoDB?](https://github.com/adonisjs/adonis-framework/issues/213)
* [Can we have mongoDB support too?](https://github.com/adonisjs/adonis-framework/issues/103)
* [Support for document based databases?](https://github.com/adonisjs/adonis-lucid/issues/9)
* [support for nosql?](https://github.com/adonisjs/adonis-lucid/issues/11)

**Comment by webreinvent** [comment] 2016-07-23 09:42
@RomainLanz checked all those links and it's mentioned it does support mongodb. I really request/recommend you to mention it on the homepage of the website because mongodb & nodejs is considered as a great bundle. 

It will be nice to write a blog or document it, to explain step by step the best practice to use mongodb with adonis-framework or if you can inbuild the support within the framework, that will be really appreciated just like Eloquent in Laravel https://laravel.com/docs/5.1/eloquent 

Thanks

**Comment by thetutlage** [comment] 2016-07-23 13:14
@webreinvent AdonisJs does not have official support for MongoDb and `Lucid` follows Active record pattern, same is followed by `Eloquent` too.

You can make use of Mongoose within AdonisJs(if you want to use MongoDb)

**Comment by webreinvent** [comment] 2016-07-23 13:27
@thetutlage okay, but do you have any plan to support MongoDb official in near future? although I understand that we can use if we want.

**Comment by thetutlage** [comment] 2016-07-24 04:19
@webreinvent Sorry, I have no plans to do so, I am not a Mongo guy, so would love if community can contribute 3rd party provider for AdonisJs.

**Comment by thetutlage** [comment] 2016-07-24 04:31
Closing as duplicate of #213 and #103

**Closed by thetutlage** 2016-07-24 04:31 UTC
Labels: 0 - Backlog, invalid

**Comment by allanfreitas** [comment] 2016-09-26 21:47
@thetutlage @RomainLanz @webreinvent 

Hi, 
I've just published a npm package that integrates
**Mongorito**(mongodb package that use ES6 generators) with **AdonisJS** :)

I hope it helps someone.

https://www.npmjs.com/package/adonis-mongorito
https://github.com/allanfreitas/adonis-mongorito
