### ISSUE TITLE
IDE with autocomplete?

### ISSUE THREAD

**Issue by eskrano** [adonisjs/adonis-framework#516] opened 2017-03-18 00:47 UTC
Hey all . I install adonisjs but my VScode dont have autocomplete, what IDE can give me good autocomplete in adonisjs?

**Comment by thetutlage** [comment] 2017-03-21 07:21
Sorry there is no official auto-complete plugin for VsCode as of now

**Comment by eskrano** [comment] 2017-03-21 19:44
@thetutlage but for other IDE?

**Comment by shekohex** [comment] 2017-06-14 20:24
Try WebStorm or Sublime Text

**Comment by thetutlage** [comment] 2017-08-21 11:33
Duplicate of https://github.com/adonisjs/adonis-framework/issues/600

**Closed by thetutlage** 2017-08-21 11:33 UTC
Labels: duplicate
