### ISSUE TITLE
Unable to get started with Adonis

### ISSUE THREAD

**Issue by KevinNTH** [adonisjs/adonis-framework#161] opened 2016-05-16 17:47 UTC
Hi,

I am on Windows 10 64 bits.
I have node v6.1.0 and npm v3.9.0

I execute these command :
* `npm install -g adonis-cli`
* `adonis new my-project`

I have an error : 
![adonis new](https://cloud.githubusercontent.com/assets/1632391/15298223/8c79dd8e-1b9e-11e6-9c21-f33ce33e50e9.png)

I `cd` into my project directory and execute `npm start` :

![adonis npm start](https://cloud.githubusercontent.com/assets/1632391/15298303/e4d88d7c-1b9e-11e6-84f8-ce40fb54b21e.png)

So I am unable to get started with Adonis.

**Comment by thetutlage** [comment] 2016-05-16 18:05
`npm install` has failed for you. Just remove the `node_modules` and re-run `npm install` and make sure it is able to install all packages.

**Comment by KevinNTH** [comment] 2016-05-16 19:41
Actually, I have tried many times.

I don't know what's wrong. I have tried with node v4.4.4 and v6.1.0, on Windows.
On my second screenshot, you can see that I have no node_modules directory before I execute `npm install`. Actually, `npm install` fails before creating the node_modules directory.

I am going to try to install Adonis on my linux distribution tomorrow, at the office. I think this issue is Windows OS specific.

**Comment by KevinNTH** [comment] 2016-05-17 08:43
Hi,

I just try to install Adonis on my linux distribution. I have tried with node v4.4.4 and v6.1.0 and npm v3.9.0.
I am not able to execute the `npm install` command, and `adonis new my-project` fails too.

**Comment by thetutlage** [comment] 2016-05-17 08:57
Can you share the errors?

**Comment by KevinNTH** [comment] 2016-05-17 09:35
Hi,

Of course, here is a screenshot : 
![adonis-new](https://cloud.githubusercontent.com/assets/1632391/15317792/4749d568-1c23-11e6-83ed-8f029da414f2.png)

You know what ? Actually, I am able to execute with success `adonis new my-project` with npm v3.8.x !!! The bug seems to be linked to npm v3.9.0 !

**Comment by thetutlage** [comment] 2016-05-17 09:37
@KevinNTH Yeah npm throws `EMISSINGARG`error. Will debug it by upgrading to `Node6.0`.

**Comment by thetutlage** [comment] 2016-05-18 12:11
@krisanalfa What's the `npm` version?

**Comment by krisanalfa** [comment] 2016-05-19 04:17
@thetutlage Mine is 3.9.0.

```
krisanalfa@localhost ~ % npm --version
3.9.0
krisanalfa@localhost ~ % node --version
v6.2.0
```

**Comment by thetutlage** [comment] 2016-05-19 06:09
The issue is with npm version `3.9.0`. This thread can help https://github.com/npm/npm/issues/12647. Everyone switched to `3.8.9` and that what I can recommend

**Comment by krisanalfa** [comment] 2016-05-19 07:24
I confirm downgrading to `3.8.*` fixed this problem.

**Comment by thetutlage** [comment] 2016-05-19 07:35
Closing this issue as not directly related to AdonisJs

**Closed by thetutlage** 2016-05-19 07:35 UTC
