### ISSUE TITLE
Cant install validator

### ISSUE THREAD

**Issue by codingphasedotcom** [adonisjs/adonis-framework#814] opened 2018-03-21 16:58 UTC
### Problem
I'm following the example of https://adonisjs.com/docs/4.1/validator
and can't install the validator. It seems to be down.

### Terminal
```
➜ crud adonis install @adonis/validator
  [1/1] ❌  Installation failed [@adonis/validator]

   ERROR  Command failed: npm i --save @adonis/validator
npm ERR! code E404
npm ERR! 404 Not Found: @adonis/validator@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/joesantosgarcia/.npm/_logs/2018-03-21T16_50_30_042Z-debug.log



   HELP  You can manually install dependencies by running npm i --save @adonis/validator

➜  crud yarn add @adonis/validator
yarn add v1.3.2
info No lockfile found.
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@adonis%2fvalidator: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/joesantosgarcia/projects/crud/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
➜  crud npm i --save @adonis/validator
npm ERR! code E404
npm ERR! 404 Not Found: @adonis/validator@latest


   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 5.5.1 → 5.7.1    │
   │     Run npm i -g npm to update      │
   │                                     │
   ╰─────────────────────────────────────╯


npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/joesantosgarcia/.npm/_logs/2018-03-21T16_54_01_386Z-debug.log

```

**Comment by RomainLanz** [comment] 2018-03-21 18:21
Closing since it's a duplicate of https://github.com/adonisjs/adonis-validation-provider/issues/45

**Closed by RomainLanz** 2018-03-21 18:21 UTC
