### ISSUE TITLE
Config.set not updating values

### ISSUE THREAD

**Issue by scsddeputy** [adonisjs/adonis-framework#441] opened 2017-01-30 17:28 UTC
I have a set of config values being set in a controller, using Config.set('key', 'value') but this is not updating the values in the config files

**Comment by thetutlage** [comment] 2017-01-30 18:55
It does not update the config file, it just updates the value in memory.

**Comment by thetutlage** [comment] 2017-01-31 08:57
Closing the issue, since it is not a bug and works as intended

**Closed by thetutlage** 2017-01-31 08:57 UTC
