### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by GianCastle** [adonisjs/adonis-framework#736] opened 2017-11-28 03:15 UTC
### Brief Description
Following the tutorial of the page I find the following error in Windows 10 build 1709
```
$ adonis serve --dev

module.js:538
    throw err;
    ^

Error: Cannot find module 'C:\Users\Giancarlos Castillo\Desktop\dev\number-game\"C:\Users\Giancarlos'    at Function.Module._resolveFilename (module.js:536:15)    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
Application crashed, make sure to kill all related running process, fix the issue and re-run the app

```
### Screenshot
![image](https://user-images.githubusercontent.com/6842883/33300831-bc232804-d3c8-11e7-93e6-bc5a6d6141e9.png)

**Comment by thetutlage** [comment] 2017-11-28 03:39
The problem is with chokidar, an internal module used by AdonisJs 

This happens coz of a space inside folder name

**Comment by thetutlage** [comment] 2017-11-30 09:20
Closing since not actionable

**Closed by thetutlage** 2017-11-30 09:20 UTC
