### ISSUE TITLE
Query Builder return null for join result and raw query in AdonisJS

### ISSUE THREAD

**Issue by behnamazimi** [adonisjs/adonis-framework#1023] opened 2019-01-14 11:15 UTC
I want to get **count** result by **Database.raw** in a **select** query of the query builder but when my main table is empty, all fields of my query are `null` except **Database.raw** result. 

Here is my query:
``` javascript
const jobs = await Database.table('jobs')
  .leftJoin('job_offers', 'job_offers.id', 'job_offers.job_id')
  .select([
    Database.raw(`'job' as type`),
    Database.raw('COUNT(jobs.id) as offers_count'),
    'jobs.id', 'title', 'jobs.description', 'jobs.created_at',
  ])
  .limit(limit).offset(offset)
```

and my query result is:
``` json
[
    {
        "type": "job",
        "offers_count": 0,
        "id": null,
        "title": null,
        "description": null,
        "created_at": null
    }
]
```

In the above query, the result must be `[]` when there are not any row in my `job` table.

**Update:**
Here is the SQL command of above query builder methods, that return `[]` as result

``` sql
SELECT 
    'job' AS type,
    jobs.id, jobs.title, description, jobs.created_at,
    COUNT(job_offers.id) as offers_count
    
    FROM jobs
LEFT JOIN job_offers ON jobs.id = job_offers.id
```

What is wrong in my query?

**Comment by behnamazimi** [comment] 2019-01-17 07:08
I really need to have an answer to this issue! :(

**Comment by RomainLanz** [comment] 2019-01-18 12:35
Hey @behnamazimi! 👋 

Could you please provide a repository with the **minimum amount of code** to reproduce the issue?

Also, if you could add the expected result it would be great.

**Comment by behnamazimi** [comment] 2019-01-18 21:08
Hi @RomainLanz,
Here is the wanted repository [https://github.com/behnamazimi/query-test-issue-1023](https://github.com/behnamazimi/query-test-issue-1023).

The result must be `[]` when there is no rows/fields in the **job** table. but it returns this as result:

```
[
    {
        "type": "job",
        "offers_count": 0,
        "id": null,
        "title": null,
        "description": null,
        "created_at": null
    }
]```

**Comment by behnamazimi** [comment] 2019-01-21 05:42
Hey @RomainLanz,
Could you realize this issue? What's your opinion?

**Comment by thetutlage** [comment] 2019-01-23 05:47
@behnamazimi I think what you are getting is the expected output. Since the nature of `COUNT` clause is to always return a row, even if the count is zero.

The best way to test that is run the query in SQL directly and see the output.

<img width="911" alt="screenshot 2019-01-23 at 11 16 48 am" src="https://user-images.githubusercontent.com/1706381/51585701-649d4400-1f00-11e9-80fd-752700a48f04.png">

**Comment by RomainLanz** [comment] 2019-01-31 12:42
Closing since no answer from issue reporter.

**Closed by RomainLanz** 2019-01-31 12:42 UTC
Labels: 🤔 Question
