### ISSUE TITLE
proxies not supported on this platform. On v8/node/iojs, make sure to pass the --harmony_proxies flag

### ISSUE THREAD

**Issue by freehosting2016** [adonisjs/adonis-framework#111] opened 2016-03-04 02:06 UTC
Hi,

When i run "node ace migration:run" command show the Error 

> proxies not supported on this platform. On v8/node/iojs, make sure to pass the --harmony_proxies flag

 .

there is any solution

**Comment by thetutlage** [comment] 2016-03-04 03:19
Duplicate of https://github.com/adonisjs/adonis-framework/issues/41

**Closed by thetutlage** 2016-03-04 03:19 UTC
