### ISSUE TITLE
Route Group Nested Properties

### ISSUE THREAD

**Issue by bagaskarawg** [adonisjs/adonis-framework#531] opened 2017-04-05 18:05 UTC
Hello, thanks for this great framework!

I just want to know, is there a way to have a nested group having the same properties as parents?

I have this code:
```
Route.group('version1', function () {
  Route.group('publicApiV1', function () {
    Route.resource('places', 'V1/PlaceController')
        .only(['index', 'show'])

    Route.resource('articles', 'V1/ArticleController')
        .only(['index', 'show'])
  })

  Route.group('adminApiV1', function () {
    Route.post('places', 'V1/PlaceController.store')
    Route.put('places/:id', 'V1/PlaceController.update')
    Route.delete('places/:id', 'V1/PlaceController.destroy')

    Route.post('articles', 'V1/ArticleController.store')
    Route.put('articles/:id', 'V1/ArticleController.update')
    Route.delete('articles/:id', 'V1/ArticleController.destroy')
  })
  .middleware('auth')
})
.prefix('api/v1')
.formats(['json'], true)
```

What I expect from this will generate these routes:
a. GET `places` with prefix of `api/v1` and formats of `json`
b. the same for GET `articles`
c. POST `places` to have prefix `api/v1` and formats of `json` also middleware of `auth`

But what I really have is this:
a. GET `places` is written to `/places` not `/api/v1/places`
b. the same for GET `articles`
c. POST `places` doesn't have `auth` middleware

For now it will work if I don't write nested groups, but it will be very useful to have this work so routing will be simpler.

Thanks, waiting for your reply!

Regards,
Bagaskara Wisnu Gunawan.

**Comment by thetutlage** [comment] 2017-04-08 07:31
Possible duplicate of https://github.com/adonisjs/adonis-framework/pull/469 and https://github.com/adonisjs/adonis-framework/issues/331

Nested groups are not supported intentionally, the idea is to keep your routes readable

**Comment by bagaskara-turboly** [comment] 2017-04-16 06:39
okay then @thetutlage, I got your point, thanks for answering and sorry for late reply, thanks!

**Closed** 2017-04-16 12:27 UTC
Labels: duplicate
