### ISSUE TITLE
Error amazon SES

### ISSUE THREAD

**Issue by GlauberF** [adonisjs/adonis-framework#895] opened 2018-06-21 13:03 UTC
I'm trying to send email via Amazon SES and it returns me error, see the screenshots below with setup and with return error.

ps: installed aws-sdk.
I created the user and validated the domain in the amzon, everything as the documentation says.

![captura de tela de 2018-06-21 10-08-35](https://user-images.githubusercontent.com/11314585/41720605-fae871bc-7539-11e8-9e2a-d57f48f7d668.png)

![captura de tela de 2018-06-21 10-08-54](https://user-images.githubusercontent.com/11314585/41720610-fe2dbcb0-7539-11e8-8175-fdbd8dde79ae.png)

**Comment by thetutlage** [comment] 2018-06-21 13:35
Duplicate of https://github.com/adonisjs/adonis-mail/issues/27

**Closed by thetutlage** 2018-06-21 13:35 UTC
