### ISSUE TITLE
Migration does not terminate (node ace migration:run, docker, CI, pipeline)

### ISSUE THREAD

**Issue by pawelsas** [adonisjs/adonis-framework#1027] opened 2019-01-23 09:19 UTC
I searched related issues but it couldn't find a solution that works for me.
The migration command `node ace migration:run --force` is a part of our CI pipeline. 
The command isn't terminating if there is 'Nothing to migrate'. Is there a simple solution for this?

Thanks!

**Comment by thetutlage** [comment] 2019-01-23 10:46
Commands will not terminate when your app creates a long lived connection to some database or 3rd party service.

Just make sure that your hooks files are not creating any long lived connections and if they are, then you can wrap them inside a conditional to only create the connection when not executing the ace command

**Comment by pawelsas** [comment] 2019-01-23 11:45
Thanks for the quick reply. Actually I don't have any hooks 🤷🏻‍♂️

**Comment by pawelsas** [comment] 2019-01-23 12:57
Server.js

```
'use strict';

const { Ignitor } = require('@adonisjs/ignitor');

new Ignitor(require('@adonisjs/fold'))
  .appRoot(__dirname)
  .fireHttpServer()
  .catch(console.error);
```

Start folder:
- app.js
- kernel.js
- routes.js

**Comment by thetutlage** [comment] 2019-01-23 13:05
What does `Next.getRequestHandler` does?

**Comment by pawelsas** [comment] 2019-01-23 13:15
It's for the routing within next.js: https://github.com/omarkhatibco/adonis-nextjs/blob/master/providers/NextProvider/index.js

It has no effect on the migration when I remove it.

**Comment by thetutlage** [comment] 2019-01-23 13:22
It's weird. Ideally the command should terminate. Can you also share the `@adonisjs/lucid` version of your app?

**Comment by RomainLanz** [comment] 2019-02-07 09:07
Hey @pawelsas! 👋 

Could you also share your migrations?
In fact, the best would be to have a repository with the minimum amount of code to reproduce the issue.

Generally the command doesn't end when there's a connection opened (Database, Redis, etc.).

**Comment by annymosse** [comment] 2019-02-12 23:42
@pawelsas did you tried `adonis migration:refresh` coz i think you made a migration for an empty migration file,i had same problem when i created lots of migrations together than i left one without setup until i moved all the migrations and i tried couple times then i knew the reason of the bug, hopfully this can help you

**Comment by pawelsas** [comment] 2019-02-25 08:41
@annymosse I have just two migration files. So unfortunately the refresh has no effect.

@RomainLanz my migrations look like this:

```
'use strict';

const Schema = use('Schema');

class UserSchema extends Schema {
	up() {
		this.create('users', (table) => {
			table.increments();
			table.string('email').notNullable().unique();
			table.string('token');
			table.boolean('is_admin').defaultTo(false);
			table.timestamps();
		});
	}

	down() {
		this.drop('users');
	}
}

module.exports = UserSchema;
```

```
'use strict';

const Schema = use('Schema');

class UsersSchema extends Schema {
	up() {
		this.table('users', (table) => {
			table.boolean('share');
		});
	}

	down() {
		this.table('users', (table) => {
			// reverse alternations
		});
	}
}

module.exports = UsersSchema;
```

If still needed, I can provide a test repo for that.

Thanks!

**Comment by martinlevesque** [comment] 2019-08-01 13:20
Same problem, that's pretty annoying - I have only a single migration doing nothing.

**Comment by annymosse** [comment] 2019-08-02 09:34
hi @pawelsas can you upload the test into a free github/gitlab repo to get a look and try it ?

**Comment by eiipaw** [comment] 2019-08-09 11:11
Same problem with default migrations. Any temporary solution to force stop it after it runs the migrations?

**Comment by thetutlage** [comment] 2019-08-10 05:09
This is kind weird, since it works fine for me. Can you please share the output of `node ace migration:run --help` command?

**Comment by eiipaw** [comment] 2019-08-11 12:20
I am running my command inside **docker-compose.yml** file like this

`command: node --harmony ace migration:run --help`

This is the output:

`web_1        | Usage:`
`web_1        |   migration:run [options]`
`web_1        | `
`web_1        | Options:`
`web_1        |   -f, --force      Forcefully run migrations in production`
`web_1        |   -s, --silent     Silent the migrations output`
`web_1        |   --seed           Seed the database after migration finished`
`web_1        |   --log            Log SQL queries instead of executing them`
`web_1        |   -a, --keep-alive Do not close the database connection`
`web_1        | `
`web_1        | About:`
`web_1        |   Run all pending migrations`

**Comment by thetutlage** [comment] 2019-08-11 12:22
Do you face the same issue, when it's not inside the docker container? Maybe test it with a sqlite connection if you don't have mysql or pg on your host machine

**Comment by martinlevesque** [comment] 2019-08-11 12:25
I'll provide the output also soon (tomorrow). In my case it's also in a docker environment, and also I am using lucid-mongo with mongodb so for me it's not possible to use sqlite.

**Comment by eiipaw** [comment] 2019-08-11 12:44
No, this happens only when using docker. I'll try with sqlite.

**Comment by thetutlage** [comment] 2019-08-11 13:09
Okay, that helps narrow it down. Lemme try with docker and see how it goes

**Comment by thetutlage** [comment] 2019-08-12 04:34
Works fine for me using the following `Dockerfile` and `docker-compose.yml`.

```sh
FROM node:10.15.3-alpine

RUN apk update && apk upgrade && \
  apk add --update git && \
  apk add --update openssh && \
  apk add --update bash && \
  apk add --update wget

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .
```

```yml
version: '3.4'
services:
  migrate:
    build:
      context: .
    command: ["node", "ace", "migration:run"]
```

and this is how the output looks like

<img width="638" alt="Screen Shot 2019-08-12 at 10 03 44 AM" src="https://user-images.githubusercontent.com/1706381/62845784-96cd9200-bce8-11e9-8c84-e46016a01d68.png">

**Comment by eiipaw** [comment] 2019-08-12 07:25
Can confirm that **this works**. Thank you.

My docker-compose service is a bit different:

`migrate:`
`   build: .`
`   command: ["node", "ace", "migration:run"]`
`   depends_on: `
`       - mysql`
`   networks: `
`     - chat`


Could you please add your solution to docs when v5 gets released?

**Comment by martinlevesque** [comment] 2019-08-12 11:28
I'm not convinced that the problem is really related to docker - I had this problem in a non docker environment.

What we should do (I think):

- Have a sample project having the issue in non docker environment. I can try to make one (I can't provide the whole project I work on as it's not open source), or maybe @pawelsas can provide it.
- Test it in docker
- ...

**Comment by thetutlage** [comment] 2019-08-12 12:38
Will need the code that can help reproduce the issue

**Comment by RomainLanz** [comment] 2019-09-09 06:59
Closing since no answer from issue reporter.

**Closed by RomainLanz** 2019-09-09 06:59 UTC
Labels: 🤔 Question
