### ISSUE TITLE
Error on execute method create on MySQL

### ISSUE THREAD

**Issue by clebersonmachi** [adonisjs/adonis-framework#932] opened 2018-08-24 14:32 UTC
Generating a strange error when I run the create or fill method

## database 
MySQL

## Package version
adonis 4.1

package.json dependencies

```
"dependencies": {
    "@adonisjs/ace": "^5.0.4",
    "@adonisjs/auth": "^3.0.6",
    "@adonisjs/bodyparser": "^2.0.4",
    "@adonisjs/cors": "^1.0.6",
    "@adonisjs/fold": "^4.0.9",
    "@adonisjs/framework": "^5.0.8",
    "@adonisjs/ignitor": "^2.0.7",
    "@adonisjs/lucid": "^5.0.4",
    "@google-cloud/translate": "^1.1.0",
    "mysql": "^2.16.0",
    "mysql2": "^1.6.1"
  },

```
I tried to change the package from mysql to mysql2, but it did not work either

## Node.js and npm version
node 10.8.0
npm 6.4.0

## Sample Code (to reproduce the issue)

if i use this code work

```
const cacheTranslation = new Translation()
cacheTranslation.user_id = auth.user.id
cacheTranslation.traducao = traducao
cacheTranslation.texto = texto
cacheTranslation.lingua = lingua
cacheTranslation.length = texto.length
```

But, if I use the method create. Not work

```
await Translation.create({
                user_id: auth.user.id,
                traducao,
                texto,
                lingua,
                length: texto.length,
})
```

return an error in from MySQL, the column 0 not exists.
the SQL executed is strange:

```
insert into `translations` (`0`, `1`, `10`, `11`, `12`, `13`, `14`, `15`, `16`, `17`, `18`, `19`, `2`, `20`, `21`, `22`, `23`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `created_at`, `updated_at`) values (DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, '2018-08-24 08:51:17', '2018-08-24 08:51:17')﻿
```

### schema and full code
if help to resolve

```
'use strict'

const Schema = use('Schema')

class TranslationSchema extends Schema {
    up () {
        this.create('translations', (table) => {

            table.increments()
            table.timestamps()
            table.integer('user_id').unsigned().nullable().references('id').inTable('users')
            table.text('texto')
            table.text('traducao')
            table.string('lingua', 5)
            table.float('length', 10, 0)

        })
    }

    down () {
        this.drop('translations')
    }
}

module.exports = TranslationSchema
```

controller code

```
'use strict'

// Imports the Google Cloud client library
const Translate = require('@google-cloud/translate')
const Helpers = use('Helpers')
const Translation = use('App/Models/Translation')

class TranslateController {

    async translate({request, response, auth}) {

        const {texto, lingua} = request.all()

        // Busca a tradução no banco de dados local
        const traducaoLocal = await Translation.query()
            .where('texto', texto)
            .where('lingua',lingua)
            .first()

        // Caso o texto seja exatamente igual
        if(traducaoLocal && texto == traducaoLocal.texto){
            return {
                traducao: traducaoLocal.traducao,
                texto,
                lingua
            }
        }

        const translate = new Translate({
            projectId: 'cim-imob-212920',
        })

        try {

            // Busca a tradução no google
            const traducoes = await translate.translate(texto, lingua)
            const traducao = traducoes[1].data.translations[0].translatedText

            // Salva no banco de dados a tradução
            /*
            const cacheTranslation = new Translation()
            cacheTranslation.user_id = auth.user.id
            cacheTranslation.traducao = traducao
            cacheTranslation.texto = texto
            cacheTranslation.lingua = lingua
            cacheTranslation.length = texto.length

            await cacheTranslation.save()
            */

            await Translation.create({
                user_id: auth.user.id,
                traducao,
                texto,
                lingua,
                length: texto.length,
            })

            return {traducao, texto, lingua}

        } catch (e) {
            return response.status(400).send({error: e})
        }


    }

}

module.exports = TranslateController

```

Thanks

**Comment by RomainLanz** [comment] 2018-08-25 10:42
Hey @clebersonmachi! 👋 

I cannot replicate your issue, could you please give me the value you are using while doing the `Translation.create()`?

**Comment by clebersonmachi** [comment] 2018-08-27 12:08
It's a simple model (default) from Adonis

```
'use strict'

const Model = use('Model')

class Translation extends Model {
}

module.exports = Translation
```

**Comment by clebersonmachi** [comment] 2018-08-27 12:17
The sent data from API it's a simple text to translate with Google Translate. I would just like to save the translated text into my database.

### sent data

```
{
	"texto": "Olá mundo, este é um texto em português que será traduzido para inglês e salvo no meu banco de dados!",
	"lingua": "en"
}
```

**Comment by RomainLanz** [comment] 2018-08-28 06:51
I mean, can you please dump the value of 

```
{
  user_id: auth.user.id,
  traducao,
  texto,
  lingua,
  length: texto.length,
}
```

**Comment by clebersonmachi** [comment] 2018-08-29 20:05
It's a simple object with the original text, the translated text and the amount of characters that exists in the original text

```
{
  user_id: 1,
  traducao: 'Hello World!',
  texto: 'Olá mundo!',
  lingua:  'en',
  length: 10
}
```

If I display on the console **(console.log)**, I can see an object similar to the one mentioned above

**Comment by RomainLanz** [comment] 2018-09-04 20:46
I'm still not able to reproduce your issue.

Please, could you provide a repository with the minimum amount of code to reproduce this issue?

**Comment by RomainLanz** [comment] 2018-09-10 12:04
Closing since no answer from issue reporter.

**Closed by RomainLanz** 2018-09-10 12:04 UTC
Labels: 🤔 Question
