### ISSUE TITLE
migration:run and migration:refresh oddly slow on Ubuntu 16.04

### ISSUE THREAD

**Issue by mfgabriel92** [adonisjs/adonis-framework#382] opened 2016-11-23 05:18 UTC
Hello,

I've switched from macOS to elementaryOS and I noticed that running the above commands is oddly slow, taking an average time of 25s, in the worst case, it took 47s.

Could it be related to, despite having HDD of 1Tb in the computer running Linux, the mac having SSD of 128Gb? My Mac's memory is only 2Gb and my PC is 6.

**Comment by thetutlage** [comment] 2016-11-23 05:58
How long does it take when you make use of the same database without Adonis. Which means if using MYSQL how time does it take to run mysql query from command line or sequel pro etc.

**Comment by mfgabriel92** [comment] 2016-11-23 06:54
Very fast, around 1s, using MySQL Workbench.

**Comment by thetutlage** [comment] 2016-11-23 06:56
Can u share the result of `./ace migration:run --log` ?

**Comment by mfgabriel92** [comment] 2016-11-23 07:00
Yes, it showed this:

```
1472093640804_User
>SQL: function () { [native code] }

1472093640808_Token
>SQL: function () { [native code] }

1473146323743_products
>SQL: function () { [native code] }
>SQL: function () { [native code] }

1474258365500_shops
>SQL: function () { [native code] }
>SQL: function () { [native code] }
>SQL: function () { [native code] }

1474266297914_UserProperties
>SQL: function () { [native code] }

1474266320676_UserActivations
>SQL: function () { [native code] }

1476338911792_LinkedAccount
>SQL: function () { [native code] }

1479195268576_Hotels
>SQL: function () { [native code] }

1479195280534_Tours
>SQL: function () { [native code] }

1479195289820_TourDates
>SQL: function () { [native code] }

1479195361233_HotelPackages
>SQL: function () { [native code] }

1479199434423_ShopProperties
>SQL: function () { [native code] }

1479283298862_Souvenirs
>SQL: function () { [native code] }

1479283298863_Transaction
>SQL: function () { [native code] }

1479351507756_ShoppingCart
>SQL: function () { [native code] }
```

**Comment by thetutlage** [comment] 2016-11-23 07:07
It is weird, it would have displayed the actual SQL queries. Lemme see what the issue is and may we have to debug it more. Thanks for reporting

**Comment by thetutlage** [comment] 2016-11-25 06:24
I have made some changes to the code, would you mind installing from the github directly https://github.com/adonisjs/adonis-lucid and now share the output of the same command

**Comment by mfgabriel92** [comment] 2016-11-25 08:11
My friend, it's all the same, the time length too.

I first run `./ace migration:reset` and then the command above to be able to see what's in the log, because if I run it after, it will say `nothing to migrate.`

I think the reason it was faster in my MacBook Air is because it has a SSD, and my computer a HDD.

**Comment by thetutlage** [comment] 2016-11-25 08:16
I mean share the output of `./ace migration:run --log`

**Comment by mfgabriel92** [comment] 2016-11-25 08:32
That's what I mean, the output is the same as I pasted previously.

**Comment by thetutlage** [comment] 2016-11-25 09:13
Can u share your `package.json` file?

**Comment by thetutlage** [comment] 2016-11-28 08:10
Closing since not much info on what is causing the slow behaviour. Please reopen when you have the SQL queries being executed

**Closed by thetutlage** 2016-11-28 08:10 UTC
