### ISSUE TITLE
Cant Reference a Provider within the context of another Service Provider.

### ISSUE THREAD

**Issue by dev4vin** [adonisjs/adonis-framework#942] opened 2018-09-05 12:35 UTC
Hi, I have a custom provider that provides a service for authentication and checking and managing user roles and permissions. I have done it this way since I needed to separate this logic out of the controller.

Apparently, in my provided service, I have to use an external service provider that links to Mongo DB.
The problem is Adonis won't reference this external MongoDB provider. It errors, it cannot find the module.

How can I reference this external provider.

**Comment by dev4vin** [comment] 2018-09-05 13:02
Here is my AuthServiceProvider that references User
`'use strict'
const User = use('App/Models/Auth/User')

const { ServiceProvider } = require('@adonisjs/fold')

class AuthService {

  static async logout (auth) {
    await auth.logout()
    return true
  }

  static async login (email, password, remember = false) {
    // retrieve user base on the form data
    const user = await User.query()
      .where('email', email)
      .where('is_active', true)
      .first()

    if (user) {
      // verify password
      const passwordVerified = await Hash.verify(password, user.password)

      if (passwordVerified) {
        // login user
        await auth.remember(!!remember).login(user)

        return response.route('home')
      }
    }
  }
}

class AuthServiceProvider extends ServiceProvider {
  /**
   * Register namespaces to the IoC container
   *
   * @method register
   *
   * @return {void}
   */
  register () {

    //
  }

  /**
   * Attach context getter when all providers have
   * been registered
   *
   * @method boot
   *
   * @return {void}
   */
  boot () {
    //
    this.app.bind('AuthService', () => AuthService)
  }
}

module.exports = AuthServiceProvider
`
Here is the User class that references MongooseProvider
`'use strict'

const BaseModel = use('MongooseModel')

/**
 * @class User
 */
class User extends BaseModel {
  static boot ({ schema }) {
    // Hooks:
    // this.addHook('preSave', () => {})
    // this.addHook('preSave', 'UserHook.method')
    // Indexes:
    // this.index({}, {background: true})
  }
  /**
   * User's schema
   */
  static get schema () {
    return {

    }
  }
}`

At this point, MongooseProvider is registered but the reference here doesn't resolve. 
When I reference the User in the controller, theirs no issue.

**Comment by dev4vin** [comment] 2018-09-05 13:32
Users Model
`const BaseModel = use('MongooseModel')

class User extends BaseModel {
  static boot ({ schema }) {

  }

  static get schema () {
    return {

    }
  }
}

module.exports = User.buildModel('User')`

AuthServiceProvide 
`const User = use('App/Models/Auth/User')

const { ServiceProvider } = require('@adonisjs/fold')

class AuthService {

  static async logout (auth) {
    await auth.logout()
    return true
  }

  static async login (email, password, remember = false) {
   
    const user = await User.query()
      .where('email', email)
      .where('is_active', true)
      .first()

    if (user) {
      const passwordVerified = await Hash.verify(password, user.password)

      if (passwordVerified) {
        await auth.remember(!!remember).login(user)
        return response.route('home')
      }
    }
  }
}

class AuthServiceProvider extends ServiceProvider {
  
  register () {

  }

  boot () {
    this.app.bind('AuthService', () => AuthService)
  }
}

module.exports = AuthServiceProvider`

**Comment by dev4vin** [comment] 2018-09-05 13:40
Users Module
```javascript
const BaseModel = use('MongooseModel')

class User extends BaseModel {
  static boot ({ schema }) {

  }
  static get schema () {
    return { }
  }
}
```
AuthServiceProvider
```javascript
const User = use('App/Models/Auth/User')

const { ServiceProvider } = require('@adonisjs/fold')

class AuthService {

  static async logout (auth) {
    await auth.logout()
    return true
  }

  static async login (email, password, remember = false) {
   
    const user = await User.query()
      .where('email', email)
      .where('is_active', true)
      .first()

    if (user) {
      const passwordVerified = await Hash.verify(password, user.password)

      if (passwordVerified) {
        await auth.remember(!!remember).login(user)
        return response.route('home')
      }
    }
  }
}

class AuthServiceProvider extends ServiceProvider {
  
  register () {

  }

  boot () {
    this.app.bind('AuthService', () => AuthService)
  }
}
```
Sorry for the previouse format.

**Comment by dev4vin** [comment] 2018-09-05 14:29
I did this in the AuthServiceProvider
```javascript 
boot () {
    this.app.use('MongooseModel')
    this.app.bind('AuthService', () => AuthService)
  }
```
It still doesn't work.

**Comment by RomainLanz** [comment] 2018-09-19 07:36
Please, read [the documentation about Service Provider](https://adonisjs.com/docs/4.1/service-providers).

**Comment by RomainLanz** [comment] 2018-09-25 07:13
Closing since no answer from issue reporter.

**Closed** 2018-09-25 07:13 UTC
Labels: 🤔 Question

**Comment by eiipaw** [comment] 2020-01-08 09:24
> Please, read [the documentation about Service Provider](https://adonisjs.com/docs/4.1/service-providers).

I am sorry but this didn't help me at all...Can you please elaborate it a bit more?

**Comment by RomainLanz** [comment] 2020-01-08 10:55
Hi @eiipaw! 👋 

If you have an issue with the framework, please open another issue instead of answering a closed one.

Also, the issue is  more a question than an issue with the framework itself.
Please use the [forum](https://forum.adonisjs.com) or the [Discord Server](https://discord.gg/vDcEjq6) for this kind of request.
